# Generated by Django 3.2.8 on 2021-12-12 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sample_volumes.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sample_volumes', '0015_alter_sample_volumes_reported_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_date', models.DateTimeField(verbose_name=sample_volumes.models.tomorrows_date)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DELETED', 'DELETED')], max_length=200, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample_volumes.district')),
                ('facilies', models.ManyToManyField(to='sample_volumes.Facility')),
            ],
        ),
    ]
