# Generated by Django 3.2.8 on 2021-12-12 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0017_rename_routes_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 13, 23, 4, 39, 435117)),
        ),
    ]
