# Generated by Django 3.2.8 on 2021-12-12 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0018_alter_route_route_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 23, 5, 13, 922408)),
        ),
    ]
