# Generated by Django 3.2.8 on 2021-12-12 21:05

from django.db import migrations, models
import sample_volumes.models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0019_alter_route_route_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_date',
            field=models.DateTimeField(default=sample_volumes.models.tomorrows_date),
        ),
    ]
