# Generated by Django 3.2.8 on 2021-12-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0021_routefacility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='facilies',
        ),
        migrations.AddField(
            model_name='route',
            name='facilies',
            field=models.ManyToManyField(
                through='sample_volumes.RouteFacility', to='sample_volumes.Facility'),
        ),
    ]
