# Generated by Django 3.2.8 on 2021-12-14 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0022_alter_route_facilies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routefacility',
            options={'ordering': ('created',)},
        ),
    ]
