# Generated by Django 3.2.8 on 2021-12-15 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0023_alter_routefacility_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='facilies',
            new_name='facilities',
        ),
    ]
