# Generated by Django 3.2.8 on 2021-12-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0024_rename_facilies_route_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
