# Generated by Django 3.2.8 on 2021-12-19 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0025_route_route_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='confirmed',
            field=models.CharField(default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='route',
            name='confirmed_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample_volumes.courier'),
        ),
    ]
