# Generated by Django 3.2.8 on 2021-12-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0026_auto_20211219_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='added_facilities',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
