# Generated by Django 3.2.8 on 2021-12-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0027_route_added_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='commcare_id',
            field=models.CharField(default='230da219-9ca8-47c7-87db-57c88e64dde9', max_length=200),
        ),
    ]
