# Generated by Django 3.2.8 on 2021-12-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0028_route_commcare_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='commcare_id',
            field=models.CharField(default='<function uuid4 at 0x00000287019ADF30>', max_length=200),
        ),
    ]
