# Generated by Django 3.2.8 on 2021-12-19 21:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0029_alter_route_commcare_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='commcare_id',
            field=models.CharField(default=uuid.uuid4, max_length=200),
        ),
    ]
