# Generated by Django 3.2.8 on 2021-12-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0030_alter_route_commcare_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='reason_for_adding_facilities',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='added_facilities',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
