# Generated by Django 3.2.8 on 2021-12-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0031_auto_20211219_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='commcare_district_group_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
