# Generated by Django 3.2.8 on 2021-12-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0033_facilitygroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitygroup',
            name='code',
            field=models.CharField(default=0, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
