# Generated by Django 3.2.8 on 2021-12-24 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0034_facilitygroup_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitygroup',
            name='facilities',
        ),
    ]
