# Generated by Django 3.2.8 on 2021-12-28 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0035_remove_facilitygroup_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='facility_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample_volumes.facilitygroup'),
        ),
    ]
