# Generated by Django 3.2.8 on 2021-12-31 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0037_trip_visit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courier',
            old_name='commcare_user_id',
            new_name='commcare_user_name',
        ),
    ]
