# Generated by Django 3.2.8 on 2021-12-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0038_rename_commcare_user_id_courier_commcare_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='commcare_user_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
