# Generated by Django 3.2.8 on 2021-12-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0039_courier_commcare_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
