# Generated by Django 3.2.8 on 2022-01-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0040_alter_visit_visit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end_km',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_km',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
