# Generated by Django 3.2.8 on 2022-01-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0041_auto_20220101_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='commcare_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facilitygroup',
            name='commcare_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(default='Facility', max_length=200),
            preserve_default=False,
        ),
    ]
