# Generated by Django 3.2.8 on 2022-01-02 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0042_auto_20220102_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitygroup',
            name='commcare_name',
        ),
    ]
