# Generated by Django 3.2.8 on 2022-01-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0043_remove_facilitygroup_commcare_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(choices=[('Health Centre', 'Health Centre'), ('District Hospital', 'District Hospital'), ('Clinic', 'Clinic'), ('Rural Community Hospital', 'Rural Community Hospital'), ('Central Hospital', 'Central Hospital')], max_length=200, null=True),
        ),
    ]
