# Generated by Django 3.2.8 on 2022-01-03 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0044_alter_facility_facility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='commcare_district_group_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='commcare_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_code',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample_volumes.facilitygroup'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(blank=True, choices=[('Health Centre', 'Health Centre'), ('District Hospital', 'District Hospital'), ('Clinic', 'Clinic'), ('Rural Community Hospital', 'Rural Community Hospital'), ('Central Hospital', 'Central Hospital')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='operator',
            field=models.CharField(blank=True, choices=[('Malawi Government', 'Malawi Government'), ('CHAM', 'CHAM'), ('Private', 'Private')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sample_volumes',
            name='reported_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(),
        ),
    ]
