# Generated by Django 3.2.8 on 2022-01-07 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0045_auto_20220104_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='facility',
        ),
        migrations.AddField(
            model_name='trip',
            name='end_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_locations', to='sample_volumes.facility'),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_locations', to='sample_volumes.facility'),
        ),
    ]
