# Generated by Django 4.0.4 on 2022-05-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0048_visit_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample_volumes',
            name='session_id',
            field=models.IntegerField(default=0),
        ),
    ]
