# Generated by Django 4.0.4 on 2022-05-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0049_sample_volumes_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.DateTimeField(auto_now_add=True)),
                ('time_completed', models.DateTimeField(null=True)),
                ('user', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
