# Generated by Django 4.0.4 on 2022-07-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0050_dataupdates'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataupdates',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
