# Generated by Django 4.0.4 on 2022-07-12 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0051_dataupdates_completed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataUpdates',
            new_name='DataUpdate',
        ),
    ]
