# Generated by Django 4.0.4 on 2022-07-12 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0052_rename_dataupdates_dataupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataupdate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
