# Generated by Django 4.0.4 on 2022-08-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0053_dataupdate_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='optimization_district',
            field=models.BooleanField(default=False),
        ),
    ]
