# Generated by Django 4.0.4 on 2023-01-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0054_district_optimization_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='commcare_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
